### ISSUE TITLE
Resnext-101 feature file cannot be accessed.

### ISSUE THREAD

**Issue by zhouMail** [zchoi/S2-Transformer#1]
Resnext-101 feature file cannot be accessed.
![1661133227184](https://user-images.githubusercontent.com/90842321/185823794-f8f68052-3159-491c-bac8-c8e11c793e13.png)

**Comment by zhouMail** [comment]
@zchoi Hello，Could you help me solve the problem?

**Comment by zchoi** [comment]
Thanks for your attention.
We are uploading our features. Besides, you can download processed COCO grid features (i.e., X101-features and X152-features) from this [repo](https://github.com/zhangxuying1004/RSTNet). Our implementation is based on their code.

**Comment by zhouMail** [comment]
@zchoi Thank you. What features file are used to obtain the evaluation scores? X101_grid_feats_coco_trainval.hdf5 or  X101_grid_feats_coco_test.hdf5？
![1661736198578](https://user-images.githubusercontent.com/90842321/187104976-63ae7a35-6ce2-4058-bb51-4329d0bbd42d.jpg)
