### ISSUE TITLE
Not able to download ResNeXT features

### ISSUE THREAD

**Issue by m22cs058** [zchoi/S2-Transformer#10]
Not able to download ResNeXT features as baidu is banned in my country. Can you please upload those in google drive?

**Comment by zchoi** [comment]
Okay, I'll upload them (ResNeXT101 and 152) to OneDrive later. I don't have enough storage on Google Drive 😥

**Comment by m22cs058** [comment]
aye chamkadar

**Comment by zchoi** [comment]
OneDrive: [**ResNeXt101**](https://1drv.ms/f/s!Am8OAR5-SGckhdBW-y1mFXD92IHvZg?e=k9Jjeh) and  [**ResNeXt152**](https://1drv.ms/f/s!Am8OAR5-SGckhdBXOKqrUbSBr5cM7g?e=IHArZ6) 

> Not able to download ResNeXT features as baidu is banned in my country. Can you please upload those in google drive?

**Comment by HudaDiab** [comment]
Not able to download ResNeXT features it shows I have to have an account or something! and everything is in Chinese, not English language, I'm not able to understand please help.
