### ISSUE TITLE
关于单卡训练文件

### ISSUE THREAD

**Issue by hzf-hhh** [zchoi/S2-Transformer#3]
作者，您好，我想问下如果我想要用单卡训练，是否可以直接将worldsize改为1就可以进行单卡训练？
以及如果我想使用rstnet模型的train_transformer文件进行训练，是否可以达到相同的评价指标

**Comment by zchoi** [comment]
是的，指定worldSize=1即为单卡训练。
您可以使用RSTNet的方式进行单卡训练，我们的代码是基于RSTNet的repo。理论上来说可以达到相同的性能，我用RSTNet的代码是能跑出CIDEr=133.5的结果的，您自己可以进行尝试和验证。

**Comment by hzf-hhh** [comment]
> 是的，指定worldSize=1即为单卡训练。 您可以使用RSTNet的方式进行单卡训练，我们的代码是基于RSTNet的repo。理论上来说可以达到相同的性能，我用RSTNet的代码是能跑出CIDEr=133.5的结果的，您自己可以进行尝试和验证。

谢谢您的回答，我正在尝试使用rstnet的训练文件进行训练，还有一个问题想请教您：我在直接使用您的tran_transformer文件进行训练，worldsize为1时，一直出现下面这个错误，想请教您一下这个问题要怎么解决？（我是直接使用nohup python -u train_transformer.py > logs1-1.log 2>&1 &这条指令进行训练）
![图片](https://user-images.githubusercontent.com/55089176/188778273-0d4beb7f-4651-45eb-8905-67e2945fb611.png)

**Comment by zchoi** [comment]
您好，我之前没有遇到这个报错，我这里设置worldSize=1是可以跑通的，如下图：
![image](https://user-images.githubusercontent.com/30498168/188782062-9055d403-c0bd-41ac-83b6-3f5feeda5160.png)
我觉得可能是版本问题导致的register_state函数注册buffer时维度错误，您可以check一下CUDA和torch的版本号，尽量和[environment.yml](https://github.com/zchoi/S2-Transformer/blob/main/environment.yaml)保持一致。

**Comment by hzf-hhh** [comment]
> 您好，我之前没有遇到这个报错，我这里设置worldSize=1是可以跑通的，如下图： ![image](https://user-images.githubusercontent.com/30498168/188782062-9055d403-c0bd-41ac-83b6-3f5feeda5160.png) 我觉得可能是版本问题导致的register_state函数注册buffer时维度错误，您可以check一下CUDA和torch的版本号，尽量和[environment.yml](https://github.com/zchoi/S2-Transformer/blob/main/environment.yaml)保持一致。

谢谢您，我在更换了torch版本后成功运行了，十分感谢，祝您生活愉快

**Comment by zchoi** [comment]
不客气~
