### ISSUE TITLE
关于实验结果指标不正常

### ISSUE THREAD

**Issue by hzf-hhh** [zchoi/S2-Transformer#4]
作者，您好，我使用您的代码进行实验结果复现，感觉实验结果始终与您的结果有所差距，想请教您是不是github上的代码与您的代码有区别，还是有哪些参数需要调整？

![1H2JSWXREJH}_)A)G~M8P`7](https://user-images.githubusercontent.com/55089176/190085362-7250ea28-da91-4a3e-aa28-78aabbed048f.jpg)
![PR23(RZJ3$2Y`CP)TIPRLPO](https://user-images.githubusercontent.com/55089176/190085386-927842a6-61fa-459a-a9f9-50d83fbf59a2.jpg)
![W7}D%UF6_)U0{`BVR2DD AV](https://user-images.githubusercontent.com/55089176/190085395-121c6bd1-bcb8-40d5-8ba9-adb4e3da0507.png)
![A}(L98P)BGWY@BX EEGD8XC](https://user-images.githubusercontent.com/55089176/190085400-c0b0917a-71d9-4876-bcb1-b37e2ad0930b.png)

**Comment by hzf-hhh** [comment]
![1H2JSWXREJH}_)A)G~M8P`7](https://user-images.githubusercontent.com/55089176/190085683-a3d648c6-6c3d-4c1a-9c06-7dbfeeff42c5.jpg)

**Comment by zchoi** [comment]
您好，github上的代码和实验代码是一致的。请问您是用几卡跑的呢，虽然在RL阶段会有波动，但不至于这么低。您可以参考 #2 ，看下在setting上时候有不同

**Comment by hzf-hhh** [comment]
> 您好，github上的代码和实验代码是一致的。请问您是用几卡跑的呢，虽然在RL阶段会有波动，但不至于这么低。您可以参考 #2 ，看下在setting上时候有不同
作者，您好，我采用torch版本与您提供的一致，我用的是双卡跑的，另外我将伪区域的个数改为6和7，发现实验结果虽然没有达到标准分数，但是都优于num=5的时候，我想请教您是为什么，是因为我的卡的问题吗/(ㄒoㄒ)/~~

**Comment by zchoi** [comment]
您好，我是用8卡V100跑的，可能在训练过程中确实会有点影响。您可以适当调整一下batch_size和学习率，跑多次尝试下

**Comment by hzf-hhh** [comment]
> 您好，我是用8卡V100跑的，可能在训练过程中确实会有点影响。您可以适当调整一下batch_size和学习率，跑多次尝试下

作者您好，我看到您论文里面是说强化学习是采用固定的学习率5e-7?
![图片](https://user-images.githubusercontent.com/55089176/194793900-0fce96ac-555c-4e9e-911d-e7319b9ffacd.png)
但是我在代码里面时看到是5e-6，我想问下哪个是正确的？

**Comment by zchoi** [comment]
您好，前段时间太忙没能及时回复。可以设置为5e-6，这是我在整理代码后重新训练模型时的学习率，得到的结果会更好一点(133.7 CIDEr score)
