### ISSUE TITLE
关于 online test 代码

### ISSUE THREAD

**Issue by zhouMail** [zchoi/S2-Transformer#5]
作者，您好，请问你能公布一下online test的代码吗？我修改并运行RSTNet的online test会报一些错误。

**Comment by zhouMail** [comment]
麻烦你上传一下在线测试的代码，可以吗？谢谢

**Comment by zchoi** [comment]
您好，前段时间在赶论文，抱歉没能及时回复。这篇论文online test的代码也是基于RSTNet的，应该可以正常运行的呀
