### ISSUE TITLE
关于X152_grid_feature的问题

### ISSUE THREAD

**Issue by zhouMail** [zchoi/S2-Transformer#7]
![image](https://user-images.githubusercontent.com/90842321/203476733-4e16ebdd-960c-470e-84f0-87ad974e8613.png)
![image](https://user-images.githubusercontent.com/90842321/203476808-192d8c2c-2743-47b5-b2d8-0fb7c9fee82f.png)
作者，你好！对于X152的特征文件处理，出现这样的问题，请问如何解决？

**Comment by zhouMail** [comment]
我个人认为有可能是你上传的X152特征文件不完整导致的，请你帮忙检查一下是否是这个问题，谢谢！

**Comment by zchoi** [comment]
![image](https://user-images.githubusercontent.com/30498168/203550229-a7634c87-530e-4292-92b6-a30dd8d98f94.png)
您好，我下载了自己上传的X152特征进行验证，并跑完了第一个epoch，好像没有遇到这个问题呀

**Comment by zhouMail** [comment]
> ![image](https://user-images.githubusercontent.com/30498168/203550229-a7634c87-530e-4292-92b6-a30dd8d98f94.png) 您好，我下载了自己上传的X152特征进行验证，并跑完了第一个epoch，好像没有遇到这个问题呀

您好，请问这个问题应该如何解决一下呀？
