### ISSUE TITLE
log文件打开乱码

### ISSUE THREAD

**Issue by krl24** [zchoi/S2-Transformer#8]
作者你好，我打开你提供的log文件是乱码的，请问怎么解决呢

**Comment by zchoi** [comment]
您好，麻烦可以提供更详细的信息吗？e.g., 哪个log文件，用什么方式打开的，或者提供下截图呢🤔

**Comment by krl24** [comment]
你好，这是我复现代码生成的log文件，用pycharm打开的，下载下来用其他工具打开也是这个状态



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haonan ***@***.***&gt;; 
发送时间: 2022年12月25日(星期天) 下午4:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zchoi/S2-Transformer] log文件打开乱码 (Issue #8)





 
您好，麻烦可以提供更详细的信息吗？e.g., 哪个log文件，用什么方式打开的，或者提供下截图呢🤔

**Comment by zchoi** [comment]
您好，您是指生成的tensorboard文件吗？

**Comment by krl24** [comment]
是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zchoi/S2-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月25日(星期天) 晚上6:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zchoi/S2-Transformer] log文件打开乱码 (Issue #8)





 
您好，您是指生成的tensorboard文件吗？

**Comment by zchoi** [comment]
尝试在你的conda环境下安装tensorboard并执行命令：`tensorboard --logdir=tensorboard_logs`尝试下呢

**Comment by krl24** [comment]
好的，已经成功了，感谢！！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zchoi/S2-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月25日(星期天) 晚上6:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zchoi/S2-Transformer] log文件打开乱码 (Issue #8)





 
尝试在你的conda环境下安装tensorboard并执行命令：tensorboard --logdir=tensorboard_logs尝试下呢
