### ISSUE TITLE
代码实现

### ISSUE THREAD

**Issue by Baixiaobai201619707** [zchoi/S2-Transformer#9]
您好，我看到您论文中说是实验是在未做任何改变的普通transformer上进行的，不过我在代码中看到有关M2的先验知识，请问这个有包含在您的结果内吗？

**Comment by Baixiaobai201619707** [comment]
> 

另外我第一次实验时只改了GPU的个数，不过复现结果有差距，请问您有什么建议吗?

**Comment by zchoi** [comment]
您好，抱歉之前一直在忙没有回复。 具体的实验是没有M<sup>2</sup>的先验知识的，您提到的先验知识是在哪一部分呢，可以cite下代码位置吗？

> 您好，我看到您论文中说是实验是在未做任何改变的普通transformer上进行的，不过我在代码中看到有关M2的先验知识，请问这个有包含在您的结果内吗？

**Comment by zchoi** [comment]
实验最终结果可能受很多因素影响，包括但不限于GPU数量，GPU的型号，Pytorch版本等等，您可以提供更详细一点的信息，我好给您提供建议

> > 
> 
> 另外我第一次实验时只改了GPU的个数，不过复现结果有差距，请问您有什么建议吗?

**Comment by zchoi** [comment]
This issue was closed because it has been inactive for 6 months since being marked as stale.

**Comment by zchoi** [comment]
This issue was closed because it has been inactive for 6 months since being marked as stale.
